export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_HOSPITALS: "VIEW_HOSPITALS",
  CREATE_TRANSFER: "CREATE_TRANSFER",
  APPROVE_TRANSFER: "APPROVE_TRANSFER",
  VIEW_REPORTS: "VIEW_REPORTS"
}