import { PERMISSIONS } from "./permissions.js";

export const ROLE_PERMISSIONS = {

  // 🔵 STATE LEVEL
  STATE_ADMIN: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_HOSPITALS,
    PERMISSIONS.APPROVE_TRANSFER,
    PERMISSIONS.VIEW_REPORTS
  ],

  DISTRICT_ADMIN: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_HOSPITALS,
    PERMISSIONS.CREATE_TRANSFER
  ],

  // 🏥 HOSPITAL ADMIN
  HOSPITAL_ADMIN: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.CREATE_TRANSFER,
    PERMISSIONS.STOCK_INWARD,
    PERMISSIONS.STOCK_OUTWARD,
    PERMISSIONS.BATCH_EDIT,
    PERMISSIONS.TRANSFER_APPROVAL,
    PERMISSIONS.AUDIT_LOG_VIEW,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.DELETE_USER
  ],

  // 👨‍⚕️ SUB USERS
  MEDICAL_SUPERINTENDENT: [
    PERMISSIONS.TRANSFER_APPROVAL,
    PERMISSIONS.VIEW_DASHBOARD
  ],

  STORE_MANAGER: [
    PERMISSIONS.STOCK_INWARD,
    PERMISSIONS.STOCK_OUTWARD,
    PERMISSIONS.BATCH_EDIT
  ],

  PHARMACIST: [
    PERMISSIONS.STOCK_INWARD,
    PERMISSIONS.STOCK_OUTWARD,
    PERMISSIONS.VIEW_DASHBOARD
  ],

  AUDITOR: [
    PERMISSIONS.AUDIT_LOG_VIEW
  ]
};